CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users(
  user_id UUID NOT NULL DEFAULT uuid_generate_v4() UNIQUE PRIMARY KEY,
  email VARCHAR(256) NOT NULL UNIQUE,
  username VARCHAR(256) NOT NULL UNIQUE,
  first_name VARCHAR(256) NOT NULL,
  last_name VARCHAR(256) NOT NULL,
  password VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders(
  order_id UUID NOT NULL DEFAULT uuid_generate_v4() UNIQUE PRIMARY KEY,
  author_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  address VARCHAR(256) NOT NULL,
  city VARCHAR(256) NOT NULL,
  country VARCHAR(256) NOT NULL,
  zip VARCHAR(256) NOT NULL,
  order_amount NUMERIC(10,2) NOT NULL,
  paid BOOLEAN NOT NULL DEFAULT FALSE,
  order_products VARCHAR(1024) NOT NULL 
);